/**
 * Oceanic Ledger design reminder: evidence-led climate-accountability data, with
 * teal reserved for emissions, coral reserved for harms, and complete source context.
 * Generated by /home/ubuntu/pacific_climate_justice_data/build_app_data.py
 */

export const climateJusticeData = {
  "points": [
    {
      "code": "TON",
      "country": "Tonga",
      "ghgPerCapita": 2.41941994,
      "ghgLatest": 2.6381912,
      "globalSharePct": 0.0005193909226627,
      "peopleAffectedTotal": 225189.0,
      "peopleAffectedPer1000": 213.81368173080156,
      "economicLossPctGDP": 8.223433184,
      "lossYears": 10,
      "affectedYears": 10,
      "emissionsLossGap": 3.398927589230334
    },
    {
      "code": "WSM",
      "country": "Samoa",
      "ghgPerCapita": 2.05803078444,
      "ghgLatest": 0.71387917,
      "globalSharePct": 0.0008307668446598,
      "peopleAffectedTotal": 18287.0,
      "peopleAffectedPer1000": 13.399298684124362,
      "economicLossPctGDP": 5.359602199999999,
      "lossYears": 7,
      "affectedYears": 7,
      "emissionsLossGap": 2.6042381098096024
    },
    {
      "code": "VUT",
      "country": "Vanuatu",
      "ghgPerCapita": 5.6384282884,
      "ghgLatest": 1.4607042,
      "globalSharePct": 0.0027612869556395,
      "peopleAffectedTotal": 1153288.0,
      "peopleAffectedPer1000": 245.9673669890233,
      "economicLossPctGDP": 3.779448186875,
      "lossYears": 16,
      "affectedYears": 16,
      "emissionsLossGap": 0.6703017212528002
    },
    {
      "code": "FJI",
      "country": "Fiji",
      "ghgPerCapita": 2.46732146,
      "ghgLatest": 1.4076506,
      "globalSharePct": 0.0046850316408424,
      "peopleAffectedTotal": 1505376.0,
      "peopleAffectedPer1000": 102.57871517705055,
      "economicLossPctGDP": 1.4645706395625,
      "lossYears": 16,
      "affectedYears": 16,
      "emissionsLossGap": 0.593587282121925
    },
    {
      "code": "FSM",
      "country": "Micronesia",
      "ghgPerCapita": 1.766147148,
      "ghgLatest": 1.8309101,
      "globalSharePct": 0.0004031038586114,
      "peopleAffectedTotal": 267032.0,
      "peopleAffectedPer1000": 214.55173012185008,
      "economicLossPctGDP": 0.4151145144444444,
      "lossYears": 9,
      "affectedYears": 9,
      "emissionsLossGap": 0.2350395973033864
    },
    {
      "code": "SLB",
      "country": "Solomon Islands",
      "ghgPerCapita": 5.879880064,
      "ghgLatest": 4.145129,
      "globalSharePct": 0.007087155232736,
      "peopleAffectedTotal": 326834.0,
      "peopleAffectedPer1000": 34.70695590263152,
      "economicLossPctGDP": 0.1614969299999999,
      "lossYears": 14,
      "affectedYears": 14,
      "emissionsLossGap": 0.0274660245178769
    },
    {
      "code": "PNG",
      "country": "Papua New Guinea",
      "ghgPerCapita": 6.029958283999999,
      "ghgLatest": 4.121168,
      "globalSharePct": 0.0974295097305317,
      "peopleAffectedTotal": 3810654.0,
      "peopleAffectedPer1000": 21.01861605607805,
      "economicLossPctGDP": 0.038671734090909,
      "lossYears": 22,
      "affectedYears": 22,
      "emissionsLossGap": 0.0064132672681204
    },
    {
      "code": "PLW",
      "country": "Palau",
      "ghgPerCapita": 15.1900899,
      "ghgLatest": 16.578695,
      "globalSharePct": 0.0005771258025974,
      "peopleAffectedTotal": 22738.0,
      "peopleAffectedPer1000": 255.38259787438187,
      "economicLossPctGDP": 0.0,
      "lossYears": 5,
      "affectedYears": 5,
      "emissionsLossGap": 0.0
    },
    {
      "code": "KIR",
      "country": "Kiribati",
      "ghgPerCapita": 0.7685915832000001,
      "ghgLatest": 0.8241486,
      "globalSharePct": 0.0001735724534924,
      "peopleAffectedTotal": 1805.0,
      "peopleAffectedPer1000": 5.18749780339281,
      "economicLossPctGDP": 0.0,
      "lossYears": 3,
      "affectedYears": 3,
      "emissionsLossGap": 0.0
    },
    {
      "code": "TUV",
      "country": "Tuvalu",
      "ghgPerCapita": 1.732557056,
      "ghgLatest": 2.0527356,
      "globalSharePct": 3.65969426119892e-05,
      "peopleAffectedTotal": 20317.0,
      "peopleAffectedPer1000": 486.6590998600036,
      "economicLossPctGDP": 0.0,
      "lossYears": 4,
      "affectedYears": 4,
      "emissionsLossGap": 0.0
    }
  ],
  "yearSeries": {
    "TON": [
      {
        "year": 2000,
        "ghgPerCapita": 1.710907,
        "globalSharePct": 0.000430689949861,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 1.6441339,
        "globalSharePct": 0.0004218721178165,
        "peopleAffected": 16500.0,
        "peopleAffectedPer1000": 159.7212138812255,
        "economicLossPctGDP": 28.324196
      },
      {
        "year": 2002,
        "ghgPerCapita": 1.6867293,
        "globalSharePct": 0.0004230239027929,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2003,
        "ghgPerCapita": 1.9013267,
        "globalSharePct": 0.0004493702300027,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2004,
        "ghgPerCapita": 1.8886245,
        "globalSharePct": 0.0004467948952595,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2005,
        "ghgPerCapita": 2.1799314,
        "globalSharePct": 0.0005118854624447,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 2.366064,
        "globalSharePct": 0.0005440190355282,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 2.1661456,
        "globalSharePct": 0.0004947547579121,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": 2.330963,
        "globalSharePct": 0.0005234266930958,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2009,
        "ghgPerCapita": 2.402486,
        "globalSharePct": 0.0005402291132785,
        "peopleAffected": 507.0,
        "peopleAffectedPer1000": 4.72863951351906,
        "economicLossPctGDP": 3.0408268
      },
      {
        "year": 2010,
        "ghgPerCapita": 2.3310618,
        "globalSharePct": 0.0005047993050313,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 2.4415345,
        "globalSharePct": 0.0005157048906555,
        "peopleAffected": 7600.0,
        "peopleAffectedPer1000": 70.6424747174301,
        "economicLossPctGDP": 0.72438604
      },
      {
        "year": 2012,
        "ghgPerCapita": 2.4126513,
        "globalSharePct": 0.0005007074343016,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2013,
        "ghgPerCapita": 2.66627,
        "globalSharePct": 0.0005524140778391,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 2.7259948,
        "globalSharePct": 0.000558043617199,
        "peopleAffected": 4014.0,
        "peopleAffectedPer1000": 37.64524932709351,
        "economicLossPctGDP": 7.029515
      },
      {
        "year": 2015,
        "ghgPerCapita": 2.6810973,
        "globalSharePct": 0.0005458460899482,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2016,
        "ghgPerCapita": 2.9569833,
        "globalSharePct": 0.0006117413290439,
        "peopleAffected": 392.0,
        "peopleAffectedPer1000": 3.714372346876895,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2017,
        "ghgPerCapita": 2.9509583,
        "globalSharePct": 0.0006014222378949,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 2.7489834,
        "globalSharePct": 0.0005567110104447,
        "peopleAffected": 87000.0,
        "peopleAffectedPer1000": 823.9416611421536,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2019,
        "ghgPerCapita": 2.9589517,
        "globalSharePct": 0.0005948596201584,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 2.704711,
        "globalSharePct": 0.0005650940760012,
        "peopleAffected": 25000.0,
        "peopleAffectedPer1000": 236.4714673527492,
        "economicLossPctGDP": 21.91201
      },
      {
        "year": 2021,
        "ghgPerCapita": 2.6675785,
        "globalSharePct": 0.0005346524357495,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2022,
        "ghgPerCapita": 2.6916685,
        "globalSharePct": 0.0005283840851531,
        "peopleAffected": 84176.0,
        "peopleAffectedPer1000": 801.2717390269673,
        "economicLossPctGDP": 21.203398
      },
      {
        "year": 2023,
        "ghgPerCapita": 2.6315515,
        "globalSharePct": 0.0005089357764923,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2024,
        "ghgPerCapita": 2.6381912,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ],
    "WSM": [
      {
        "year": 2000,
        "ghgPerCapita": 0.2845633,
        "globalSharePct": 0.0001267391820898,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 0.38932407,
        "globalSharePct": 0.0001771321447461,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.5632754
      },
      {
        "year": 2002,
        "ghgPerCapita": 0.36209232,
        "globalSharePct": 0.0001612602931035,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2003,
        "ghgPerCapita": 0.32119685,
        "globalSharePct": 0.0001347414819872,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2004,
        "ghgPerCapita": 0.27660465,
        "globalSharePct": 0.0001159845628775,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2005,
        "ghgPerCapita": 0.25812426,
        "globalSharePct": 0.0001072444680713,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2006,
        "ghgPerCapita": 0.20241825,
        "globalSharePct": 8.221721099436025e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 0.082778655,
        "globalSharePct": 3.343497480196228e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": -0.018164614,
        "globalSharePct": -7.244989190317167e-06,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2009,
        "ghgPerCapita": 1.1277128,
        "globalSharePct": 0.0004529817293674,
        "peopleAffected": 5584.0,
        "peopleAffectedPer1000": 29.15470161332428,
        "economicLossPctGDP": 19.7514
      },
      {
        "year": 2010,
        "ghgPerCapita": 2.6497502,
        "globalSharePct": 0.0010311955295952,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 3.7418468,
        "globalSharePct": 0.0014305420970408,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2012,
        "ghgPerCapita": 4.6851964,
        "globalSharePct": 0.001777903248945,
        "peopleAffected": 12703.0,
        "peopleAffectedPer1000": 64.64038917554626,
        "economicLossPctGDP": 17.20254
      },
      {
        "year": 2013,
        "ghgPerCapita": 5.51676,
        "globalSharePct": 0.0021162710413888,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 6.244031,
        "globalSharePct": 0.0023981796253964,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2015,
        "ghgPerCapita": 5.7041717,
        "globalSharePct": 0.002208524149928,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2016,
        "ghgPerCapita": 4.406389,
        "globalSharePct": 0.0017578619899563,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2017,
        "ghgPerCapita": 3.4962287,
        "globalSharePct": 0.0013891078513694,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 2.7253184,
        "globalSharePct": 0.001085098194993,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2019,
        "ghgPerCapita": 2.2692952,
        "globalSharePct": 0.0009055970346755,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 1.8013855,
        "globalSharePct": 0.0007545587357213,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2021,
        "ghgPerCapita": 1.873251,
        "globalSharePct": 0.0007608040905491,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2022,
        "ghgPerCapita": 1.3628929,
        "globalSharePct": 0.0005482327012612,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 0.9737231,
        "globalSharePct": 0.0003900369221669,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2024,
        "ghgPerCapita": 0.71387917,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ],
    "VUT": [
      {
        "year": 2000,
        "ghgPerCapita": 12.118555,
        "globalSharePct": 0.0055338759064886,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 9.5903635,
        "globalSharePct": 0.0045509030938203,
        "peopleAffected": 5300.0,
        "peopleAffectedPer1000": 27.74186456735777,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2002,
        "ghgPerCapita": 8.9798565,
        "globalSharePct": 0.0042461337527531,
        "peopleAffected": 4004.0,
        "peopleAffectedPer1000": 20.44202561890224,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2003,
        "ghgPerCapita": 24.36442,
        "globalSharePct": 0.0110647981210079,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2004,
        "ghgPerCapita": 17.688139,
        "globalSharePct": 0.0081915882548591,
        "peopleAffected": 54008.0,
        "peopleAffectedPer1000": 262.531596344546,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2005,
        "ghgPerCapita": 13.1052265,
        "globalSharePct": 0.0061373116083199,
        "peopleAffected": 5000.0,
        "peopleAffectedPer1000": 23.722316057161294,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2006,
        "ghgPerCapita": 10.265899,
        "globalSharePct": 0.0047964657539771,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2007,
        "ghgPerCapita": 6.8687096,
        "globalSharePct": 0.0032523536873147,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": 5.846042,
        "globalSharePct": 0.0027829304630298,
        "peopleAffected": 1847.0,
        "peopleAffectedPer1000": 8.139862851904738,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2009,
        "ghgPerCapita": 5.2270894,
        "globalSharePct": 0.0025513869209602,
        "peopleAffected": 8503.0,
        "peopleAffectedPer1000": 36.53433015381971,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2010,
        "ghgPerCapita": 3.9813673,
        "globalSharePct": 0.0019123884827169,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 2.915906,
        "globalSharePct": 0.0013939039886767,
        "peopleAffected": 32000.0,
        "peopleAffectedPer1000": 131.42601331509798,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2012,
        "ghgPerCapita": 2.6760404,
        "globalSharePct": 0.0012861306262373,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2013,
        "ghgPerCapita": 2.2423806,
        "globalSharePct": 0.0011040483896766,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 1.7824322,
        "globalSharePct": 0.0008905835783351,
        "peopleAffected": 20006.0,
        "peopleAffectedPer1000": 76.87312437799474,
        "economicLossPctGDP": 0.22748329
      },
      {
        "year": 2015,
        "ghgPerCapita": 1.1548698,
        "globalSharePct": 0.0005896627498735,
        "peopleAffected": 188000.0,
        "peopleAffectedPer1000": 706.4614922120136,
        "economicLossPctGDP": 52.53927
      },
      {
        "year": 2016,
        "ghgPerCapita": 0.57103586,
        "globalSharePct": 0.0003045828572107,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2017,
        "ghgPerCapita": 3.2758193,
        "globalSharePct": 0.0017646568661588,
        "peopleAffected": 13564.0,
        "peopleAffectedPer1000": 48.700622580946295,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2018,
        "ghgPerCapita": 1.8817672,
        "globalSharePct": 0.0010295832466719,
        "peopleAffected": 13586.0,
        "peopleAffectedPer1000": 47.62455612693805,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2019,
        "ghgPerCapita": 0.94337505,
        "globalSharePct": 0.0005239752031044,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 0.80925375,
        "globalSharePct": 0.0004779707382417,
        "peopleAffected": 130120.0,
        "peopleAffectedPer1000": 435.3776094383121,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2021,
        "ghgPerCapita": 0.74330145,
        "globalSharePct": 0.0004319209969958,
        "peopleAffected": 3383.0,
        "peopleAffectedPer1000": 11.059820453638986,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2022,
        "ghgPerCapita": 1.1272608,
        "globalSharePct": 0.0006594366341122,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 1.3408928,
        "globalSharePct": 0.000794295014806,
        "peopleAffected": 593702.0,
        "peopleAffectedPer1000": 1852.875270736716,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2024,
        "ghgPerCapita": 1.4607042,
        "globalSharePct": null,
        "peopleAffected": 80265.0,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": 7.7044177
      }
    ],
    "FJI": [
      {
        "year": 2000,
        "ghgPerCapita": 2.9811664,
        "globalSharePct": 0.0061450627132699,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 3.053889,
        "globalSharePct": 0.006444557686365,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2002,
        "ghgPerCapita": 2.6143708,
        "globalSharePct": 0.0054154862306854,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2003,
        "ghgPerCapita": 2.6465232,
        "globalSharePct": 0.0051862416197754,
        "peopleAffected": 30000.0,
        "peopleAffectedPer1000": 34.63015570872345,
        "economicLossPctGDP": 1.3040686
      },
      {
        "year": 2004,
        "ghgPerCapita": 2.9065163,
        "globalSharePct": 0.0057210661731224,
        "peopleAffected": 5600.0,
        "peopleAffectedPer1000": 6.404618644988557,
        "economicLossPctGDP": 0.14770621
      },
      {
        "year": 2005,
        "ghgPerCapita": 2.5341733,
        "globalSharePct": 0.0049683783627646,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 2.847938,
        "globalSharePct": 0.0054864866137675,
        "peopleAffected": 392.0,
        "peopleAffectedPer1000": 0.4402664061008344,
        "economicLossPctGDP": 0.016253263
      },
      {
        "year": 2007,
        "ghgPerCapita": 3.7583008,
        "globalSharePct": 0.0072202261218561,
        "peopleAffected": 969.0,
        "peopleAffectedPer1000": 1.0792532770205927,
        "economicLossPctGDP": 1.1145202
      },
      {
        "year": 2008,
        "ghgPerCapita": 2.0296452,
        "globalSharePct": 0.0038467350105814,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.85150206
      },
      {
        "year": 2009,
        "ghgPerCapita": 1.8653437,
        "globalSharePct": 0.0035491981878891,
        "peopleAffected": 14401.0,
        "peopleAffectedPer1000": 15.873278309789605,
        "economicLossPctGDP": 1.9698501
      },
      {
        "year": 2010,
        "ghgPerCapita": 2.2902398,
        "globalSharePct": 0.0042036457939525,
        "peopleAffected": 39101.0,
        "peopleAffectedPer1000": 42.94797935474234,
        "economicLossPctGDP": 1.2555703
      },
      {
        "year": 2011,
        "ghgPerCapita": 2.19683,
        "globalSharePct": 0.0039377999057645,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2012,
        "ghgPerCapita": 2.1917846,
        "globalSharePct": 0.0038722106894596,
        "peopleAffected": 27945.0,
        "peopleAffectedPer1000": 30.54365408997508,
        "economicLossPctGDP": 2.4521477
      },
      {
        "year": 2013,
        "ghgPerCapita": 2.8317828,
        "globalSharePct": 0.0050202473558843,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 2.0075312,
        "globalSharePct": 0.0035366040014384,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2015,
        "ghgPerCapita": 2.7917466,
        "globalSharePct": 0.004920357505606,
        "peopleAffected": 67000.0,
        "peopleAffectedPer1000": 72.93826918575853,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2016,
        "ghgPerCapita": 2.63917,
        "globalSharePct": 0.0047553239784199,
        "peopleAffected": 545558.0,
        "peopleAffectedPer1000": 593.5352335321003,
        "economicLossPctGDP": 12.169858
      },
      {
        "year": 2017,
        "ghgPerCapita": 2.288575,
        "globalSharePct": 0.004066822700055,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 2.822934,
        "globalSharePct": 0.0049658382744291,
        "peopleAffected": 179200.0,
        "peopleAffectedPer1000": 195.3804303384813,
        "economicLossPctGDP": 1.0749942
      },
      {
        "year": 2019,
        "ghgPerCapita": 2.5088358,
        "globalSharePct": 0.0043661600120903,
        "peopleAffected": 7780.0,
        "peopleAffectedPer1000": 8.503605834916375,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2020,
        "ghgPerCapita": 2.4621983,
        "globalSharePct": 0.0044521417299827,
        "peopleAffected": 205115.0,
        "peopleAffectedPer1000": 224.1765039547701,
        "economicLossPctGDP": 0.33398616
      },
      {
        "year": 2021,
        "ghgPerCapita": 2.3454566,
        "globalSharePct": 0.004084590998618,
        "peopleAffected": 82751.0,
        "peopleAffectedPer1000": 90.26876313108284,
        "economicLossPctGDP": 0.24044974
      },
      {
        "year": 2022,
        "ghgPerCapita": 2.2774007,
        "globalSharePct": 0.0039127029014684,
        "peopleAffected": 69564.0,
        "peopleAffectedPer1000": 75.66008431329044,
        "economicLossPctGDP": 0.5022237
      },
      {
        "year": 2023,
        "ghgPerCapita": 1.3830338,
        "globalSharePct": 0.0023628748129725,
        "peopleAffected": 230000.0,
        "peopleAffectedPer1000": 248.87734675106853,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2024,
        "ghgPerCapita": 1.4076506,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ],
    "FSM": [
      {
        "year": 2000,
        "ghgPerCapita": 2.1119509,
        "globalSharePct": 0.000580163762042,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 1.9778854,
        "globalSharePct": 0.0005520834398857,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2002,
        "ghgPerCapita": 1.8495444,
        "globalSharePct": 0.0005021487899324,
        "peopleAffected": 1623.0,
        "peopleAffectedPer1000": 14.431284677763552,
        "economicLossPctGDP": 0.21038963
      },
      {
        "year": 2003,
        "ghgPerCapita": 1.9552503,
        "globalSharePct": 0.0004966890813121,
        "peopleAffected": 1000.0,
        "peopleAffectedPer1000": 8.904878092218919,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2004,
        "ghgPerCapita": 1.7980496,
        "globalSharePct": 0.000453098419391,
        "peopleAffected": 6008.0,
        "peopleAffectedPer1000": 53.67208926290212,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2005,
        "ghgPerCapita": 1.5455436,
        "globalSharePct": 0.0003826177746839,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 1.5559127,
        "globalSharePct": 0.0003728027421118,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 1.7072741,
        "globalSharePct": 0.0004014615885091,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": 1.5805898,
        "globalSharePct": 0.0003612643163933,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2009,
        "ghgPerCapita": 1.92073,
        "globalSharePct": 0.0004349173600483,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2010,
        "ghgPerCapita": 1.517401,
        "globalSharePct": 0.0003290388281893,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 1.6299082,
        "globalSharePct": 0.0003446814663022,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2012,
        "ghgPerCapita": 1.6624674,
        "globalSharePct": 0.0003464054914563,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2013,
        "ghgPerCapita": 1.7248352,
        "globalSharePct": 0.0003608322824872,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 1.7591761,
        "globalSharePct": 0.0003661361192148,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2015,
        "ghgPerCapita": 1.7908404,
        "globalSharePct": 0.0003735903091023,
        "peopleAffected": 35000.0,
        "peopleAffectedPer1000": 321.90716197448654,
        "economicLossPctGDP": 3.525641
      },
      {
        "year": 2016,
        "ghgPerCapita": 1.7919718,
        "globalSharePct": 0.0003832008567244,
        "peopleAffected": 100000.0,
        "peopleAffectedPer1000": 916.6911117629804,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2017,
        "ghgPerCapita": 1.7765669,
        "globalSharePct": 0.0003762382271415,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 1.7745798,
        "globalSharePct": 0.0003741337711002,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2019,
        "ghgPerCapita": 1.7912747,
        "globalSharePct": 0.0003758037207113,
        "peopleAffected": 10000.0,
        "peopleAffectedPer1000": 90.66758543153236,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2020,
        "ghgPerCapita": 1.7660453,
        "globalSharePct": 0.000387159104868,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2021,
        "ghgPerCapita": 1.7692833,
        "globalSharePct": 0.0003752175736806,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2022,
        "ghgPerCapita": 1.786799,
        "globalSharePct": 0.0003743572374969,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 1.7788887,
        "globalSharePct": 0.0003704503438903,
        "peopleAffected": 34936.0,
        "peopleAffectedPer1000": 310.1397297729169,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2024,
        "ghgPerCapita": 1.8309101,
        "globalSharePct": null,
        "peopleAffected": 78465.0,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": 0.0
      }
    ],
    "SLB": [
      {
        "year": 2000,
        "ghgPerCapita": 3.5796783,
        "globalSharePct": 0.0038650953681459,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 3.9794269,
        "globalSharePct": 0.0044393732641514,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2002,
        "ghgPerCapita": 4.5260577,
        "globalSharePct": 0.0050007179295787,
        "peopleAffected": 1110.0,
        "peopleAffectedPer1000": 2.425296497959255,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2003,
        "ghgPerCapita": 4.7090325,
        "globalSharePct": 0.0049657019581768,
        "peopleAffected": 425.0,
        "peopleAffectedPer1000": 0.9116963128855938,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2004,
        "ghgPerCapita": 6.768434,
        "globalSharePct": 0.0072317242832386,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2005,
        "ghgPerCapita": 7.153544,
        "globalSharePct": 0.0076783875199856,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 5.5658007,
        "globalSharePct": 0.0059201753067633,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 5.9716215,
        "globalSharePct": 0.0063909738014062,
        "peopleAffected": 2384.0,
        "peopleAffectedPer1000": 4.766398490107324,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2008,
        "ghgPerCapita": 6.8192215,
        "globalSharePct": 0.0072790419586506,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2009,
        "ghgPerCapita": 7.898715,
        "globalSharePct": 0.0085833597127555,
        "peopleAffected": 7000.0,
        "peopleAffectedPer1000": 13.50960146675673,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2010,
        "ghgPerCapita": 7.1928444,
        "globalSharePct": 0.0077287337549203,
        "peopleAffected": 17938.0,
        "peopleAffectedPer1000": 33.656299720812946,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2011,
        "ghgPerCapita": 6.8402915,
        "globalSharePct": 0.0074260428770786,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2012,
        "ghgPerCapita": 5.6710286,
        "globalSharePct": 0.0062815436365423,
        "peopleAffected": 4836.0,
        "peopleAffectedPer1000": 8.430624295050931,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2013,
        "ghgPerCapita": 9.074025,
        "globalSharePct": 0.0104443502438777,
        "peopleAffected": 13556.0,
        "peopleAffectedPer1000": 22.78503139749089,
        "economicLossPctGDP": 0.31106475
      },
      {
        "year": 2014,
        "ghgPerCapita": 6.8400106,
        "globalSharePct": 0.008101361962593,
        "peopleAffected": 52000.0,
        "peopleAffectedPer1000": 84.29038036034137,
        "economicLossPctGDP": 1.7969764
      },
      {
        "year": 2015,
        "ghgPerCapita": 7.4246845,
        "globalSharePct": 0.0091089343354353,
        "peopleAffected": 44496.0,
        "peopleAffectedPer1000": 69.58773769476544,
        "economicLossPctGDP": 0.15291587
      },
      {
        "year": 2016,
        "ghgPerCapita": 6.8937697,
        "globalSharePct": 0.0089513160663567,
        "peopleAffected": 9770.0,
        "peopleAffectedPer1000": 14.749685606752548,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2017,
        "ghgPerCapita": 6.648762,
        "globalSharePct": 0.008817539913027,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 5.805621,
        "globalSharePct": 0.007895808051057,
        "peopleAffected": 1000.0,
        "peopleAffectedPer1000": 1.4102204315556564,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2019,
        "ghgPerCapita": 5.281922,
        "globalSharePct": 0.0073158930810998,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 4.8780093,
        "globalSharePct": 0.0071770978543136,
        "peopleAffected": 150000.0,
        "peopleAffectedPer1000": 201.4761485819437,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2021,
        "ghgPerCapita": 4.5819163,
        "globalSharePct": 0.0066378273348947,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2022,
        "ghgPerCapita": 4.451848,
        "globalSharePct": 0.0064975968609288,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 4.2956076,
        "globalSharePct": 0.0063531285106861,
        "peopleAffected": 22319.0,
        "peopleAffectedPer1000": 27.89826178041884,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2024,
        "ghgPerCapita": 4.145129,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ],
    "PNG": [
      {
        "year": 2000,
        "ghgPerCapita": 6.7632933,
        "globalSharePct": 0.0917967094865101,
        "peopleAffected": 5000.0,
        "peopleAffectedPer1000": 0.9030049838651067,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2001,
        "ghgPerCapita": 6.549087,
        "globalSharePct": 0.0931836523493896,
        "peopleAffected": 201.0,
        "peopleAffectedPer1000": 0.0350880623080194,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2002,
        "ghgPerCapita": 6.057684,
        "globalSharePct": 0.086631638925566,
        "peopleAffected": 18644.0,
        "peopleAffectedPer1000": 3.1471925266837832,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2003,
        "ghgPerCapita": 5.87524,
        "globalSharePct": 0.0813900618977687,
        "peopleAffected": 621.0,
        "peopleAffectedPer1000": 0.1014042281154244,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2004,
        "ghgPerCapita": 6.3308387,
        "globalSharePct": 0.0901861937156015,
        "peopleAffected": 19600.0,
        "peopleAffectedPer1000": 3.097324575279368,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2005,
        "ghgPerCapita": 6.596724,
        "globalSharePct": 0.0957976314300289,
        "peopleAffected": 17693.0,
        "peopleAffectedPer1000": 2.7070466905501225,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2006,
        "ghgPerCapita": 9.946257,
        "globalSharePct": 0.1452145930717066,
        "peopleAffected": 25999.0,
        "peopleAffectedPer1000": 3.8530028791930433,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2007,
        "ghgPerCapita": 8.628288,
        "globalSharePct": 0.1285588284693018,
        "peopleAffected": 162140.0,
        "peopleAffectedPer1000": 23.28475951168927,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2008,
        "ghgPerCapita": 8.454737,
        "globalSharePct": 0.1274080021473116,
        "peopleAffected": 75300.0,
        "peopleAffectedPer1000": 10.48308214309282,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2009,
        "ghgPerCapita": 6.64339,
        "globalSharePct": 0.1031916939192175,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2010,
        "ghgPerCapita": 5.454877,
        "globalSharePct": 0.0839479443064275,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 5.434284,
        "globalSharePct": 0.0838531926625898,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2012,
        "ghgPerCapita": 5.346115,
        "globalSharePct": 0.083426240294388,
        "peopleAffected": 200000.0,
        "peopleAffectedPer1000": 24.7481994447494,
        "economicLossPctGDP": 0.12678932
      },
      {
        "year": 2013,
        "ghgPerCapita": 5.6055727,
        "globalSharePct": 0.0900406999096923,
        "peopleAffected": 35000.0,
        "peopleAffectedPer1000": 4.215496163898491,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2014,
        "ghgPerCapita": 5.7579556,
        "globalSharePct": 0.0942234825082043,
        "peopleAffected": 40726.0,
        "peopleAffectedPer1000": 4.778117755272519,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2015,
        "ghgPerCapita": 5.401027,
        "globalSharePct": 0.0906046338693134,
        "peopleAffected": 2549199.0,
        "peopleAffectedPer1000": 291.56204782959924,
        "economicLossPctGDP": 0.2761994
      },
      {
        "year": 2016,
        "ghgPerCapita": 8.408042,
        "globalSharePct": 0.1477081363358764,
        "peopleAffected": 6600.0,
        "peopleAffectedPer1000": 0.7364660142693638,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2017,
        "ghgPerCapita": 6.0157695,
        "globalSharePct": 0.1067972899622864,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 5.159908,
        "globalSharePct": 0.0929718268506943,
        "peopleAffected": 545036.0,
        "peopleAffectedPer1000": 58.01638785512999,
        "economicLossPctGDP": 0.25300935
      },
      {
        "year": 2019,
        "ghgPerCapita": 4.8055296,
        "globalSharePct": 0.0878356898667638,
        "peopleAffected": 16801.0,
        "peopleAffectedPer1000": 1.7484624332944043,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2020,
        "ghgPerCapita": 4.5892067,
        "globalSharePct": 0.0890224254777068,
        "peopleAffected": 61000.0,
        "peopleAffectedPer1000": 6.214506634902728,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2021,
        "ghgPerCapita": 4.481024,
        "globalSharePct": 0.0852358856024265,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2022,
        "ghgPerCapita": 4.09425,
        "globalSharePct": 0.0780601668897892,
        "peopleAffected": 1969.0,
        "peopleAffectedPer1000": 0.1929791083698734,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2023,
        "ghgPerCapita": 4.228689,
        "globalSharePct": 0.0812216135841998,
        "peopleAffected": 16274.0,
        "peopleAffectedPer1000": 1.5663683373761434,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2024,
        "ghgPerCapita": 4.121168,
        "globalSharePct": null,
        "peopleAffected": 12851.0,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": 0.19478008
      }
    ],
    "PLW": [
      {
        "year": 2000,
        "ghgPerCapita": 15.049921,
        "globalSharePct": 0.0007085331592441,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 14.9584055,
        "globalSharePct": 0.0007200107189111,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2002,
        "ghgPerCapita": 12.934827,
        "globalSharePct": 0.0006097478587355,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2003,
        "ghgPerCapita": 13.06563,
        "globalSharePct": 0.0005817439535703,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2004,
        "ghgPerCapita": 13.08604,
        "globalSharePct": 0.0005844956147098,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2005,
        "ghgPerCapita": 15.128788,
        "globalSharePct": 0.0006668080846885,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 15.373966,
        "globalSharePct": 0.0006525137145281,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 16.019604,
        "globalSharePct": 0.0006623806950631,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": 13.852896,
        "globalSharePct": 0.0005530861696925,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2009,
        "ghgPerCapita": 14.369714,
        "globalSharePct": 0.0005646383463701,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2010,
        "ghgPerCapita": 14.623084,
        "globalSharePct": 0.0005430360087898,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 14.705599,
        "globalSharePct": 0.0005225501736871,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2012,
        "ghgPerCapita": 19.374088,
        "globalSharePct": 0.0006655790059975,
        "peopleAffected": 1250.0,
        "peopleAffectedPer1000": 70.26024394356698,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2013,
        "ghgPerCapita": 16.215145,
        "globalSharePct": 0.0005543153600041,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2014,
        "ghgPerCapita": 15.627918,
        "globalSharePct": 0.0005322683847463,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2015,
        "ghgPerCapita": 14.739879,
        "globalSharePct": 0.000503147816033,
        "peopleAffected": 7138.0,
        "peopleAffectedPer1000": 401.2140970153448,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2016,
        "ghgPerCapita": 15.038397,
        "globalSharePct": 0.0005254423094942,
        "peopleAffected": 7062.0,
        "peopleAffectedPer1000": 396.2073608617594,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2017,
        "ghgPerCapita": 15.591494,
        "globalSharePct": 0.0005379240438538,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 15.239857,
        "globalSharePct": 0.0005215352544083,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2019,
        "ghgPerCapita": 15.581647,
        "globalSharePct": 0.0005281975291172,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 15.239232,
        "globalSharePct": 0.0005365822294101,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2021,
        "ghgPerCapita": 15.5112,
        "globalSharePct": 0.0005247716287776,
        "peopleAffected": 7288.0,
        "peopleAffectedPer1000": 409.23128755123815,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2022,
        "ghgPerCapita": 15.9890175,
        "globalSharePct": 0.0005313380586471,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 15.8572035,
        "globalSharePct": 0.0005203731438583,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2024,
        "ghgPerCapita": 16.578695,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ],
    "KIR": [
      {
        "year": 2000,
        "ghgPerCapita": 0.67272115,
        "globalSharePct": 0.0001461553328954,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 0.6247517,
        "globalSharePct": 0.0001402031917378,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2002,
        "ghgPerCapita": 0.7068799,
        "globalSharePct": 0.0001574751598758,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2003,
        "ghgPerCapita": 0.6957233,
        "globalSharePct": 0.0001482337052894,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2004,
        "ghgPerCapita": 0.7245951,
        "globalSharePct": 0.0001567509421775,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2005,
        "ghgPerCapita": 0.7562404,
        "globalSharePct": 0.0001647426515659,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 0.7833105,
        "globalSharePct": 0.0001695308769589,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 0.77400655,
        "globalSharePct": 0.0001690629384885,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": 0.72932005,
        "globalSharePct": 0.0001594859168968,
        "peopleAffected": 85.0,
        "peopleAffectedPer1000": 0.8154650549239699,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2009,
        "ghgPerCapita": 0.7153756,
        "globalSharePct": 0.0001597509516212,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2010,
        "ghgPerCapita": 0.80828226,
        "globalSharePct": 0.0001771579046095,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 0.76383317,
        "globalSharePct": 0.0001659510012534,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2012,
        "ghgPerCapita": 0.7596895,
        "globalSharePct": 0.0001647277609911,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2013,
        "ghgPerCapita": 0.75414217,
        "globalSharePct": 0.0001661018020282,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 0.7498712,
        "globalSharePct": 0.0001660499647054,
        "peopleAffected": 220.0,
        "peopleAffectedPer1000": 1.907420733663375,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2015,
        "ghgPerCapita": 0.7789236,
        "globalSharePct": 0.0001745965602632,
        "peopleAffected": 1500.0,
        "peopleAffectedPer1000": 12.839607621591083,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2016,
        "ghgPerCapita": 0.74430907,
        "globalSharePct": 0.0001728804964619,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2017,
        "ghgPerCapita": 0.8612976,
        "globalSharePct": 0.0002003837990921,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 0.8533907,
        "globalSharePct": 0.0001998424762661,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2019,
        "ghgPerCapita": 0.8463619,
        "globalSharePct": 0.0001995154259021,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 0.8354044,
        "globalSharePct": 0.0002082020056483,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2021,
        "ghgPerCapita": 0.82608813,
        "globalSharePct": 0.0002014804204753,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2022,
        "ghgPerCapita": 0.81833553,
        "globalSharePct": 0.0001995285460291,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 0.8077875,
        "globalSharePct": 0.0001979290525843,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2024,
        "ghgPerCapita": 0.8241486,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ],
    "TUV": [
      {
        "year": 2000,
        "ghgPerCapita": 1.5558695,
        "globalSharePct": 3.648317102474867e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2001,
        "ghgPerCapita": 1.549308,
        "globalSharePct": 3.697371206857661e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2002,
        "ghgPerCapita": 1.9398565,
        "globalSharePct": 4.516749128711305e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2003,
        "ghgPerCapita": 1.9267389,
        "globalSharePct": 4.234244195022836e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2004,
        "ghgPerCapita": 1.9032925,
        "globalSharePct": 4.215663653019842e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2005,
        "ghgPerCapita": 1.8802092,
        "globalSharePct": 4.1625610733545295e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2006,
        "ghgPerCapita": 1.858942,
        "globalSharePct": 4.053530720616732e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2007,
        "ghgPerCapita": 1.8405014,
        "globalSharePct": 4.018513795166932e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2008,
        "ghgPerCapita": 1.4688592,
        "globalSharePct": 3.18756680401454e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2009,
        "ghgPerCapita": 1.8064638,
        "globalSharePct": 3.970036232609355e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2010,
        "ghgPerCapita": 1.7780845,
        "globalSharePct": 3.812325011966408e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2011,
        "ghgPerCapita": 1.7529033,
        "globalSharePct": 3.718204150400479e-05,
        "peopleAffected": 0.0,
        "peopleAffectedPer1000": 0.0,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2012,
        "ghgPerCapita": 1.7329568,
        "globalSharePct": 3.667551979720958e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2013,
        "ghgPerCapita": 1.3922634,
        "globalSharePct": 2.9704188404850625e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2014,
        "ghgPerCapita": 1.398816,
        "globalSharePct": 2.9560072130916364e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2015,
        "ghgPerCapita": 1.4054619,
        "globalSharePct": 2.9622414328621016e-05,
        "peopleAffected": 4613.0,
        "peopleAffectedPer1000": 419.9362767410105,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2016,
        "ghgPerCapita": 1.4118743,
        "globalSharePct": 3.030875748814827e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2017,
        "ghgPerCapita": 1.4212689,
        "globalSharePct": 2.9941320543335524e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2018,
        "ghgPerCapita": 1.7820977,
        "globalSharePct": 3.68284712826776e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2019,
        "ghgPerCapita": 1.8175045,
        "globalSharePct": 3.665685402169242e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2020,
        "ghgPerCapita": 1.85076,
        "globalSharePct": 3.812250826232003e-05,
        "peopleAffected": 5500.0,
        "peopleAffectedPer1000": 527.6791710639931,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2021,
        "ghgPerCapita": 1.890463,
        "globalSharePct": 3.668169969793972e-05,
        "peopleAffected": 10204.0,
        "peopleAffectedPer1000": 999.0209516350108,
        "economicLossPctGDP": 0.0
      },
      {
        "year": 2022,
        "ghgPerCapita": 1.9316686,
        "globalSharePct": 3.6138752627028623e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2023,
        "ghgPerCapita": 1.9650269,
        "globalSharePct": 3.5735233360846234e-05,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      },
      {
        "year": 2024,
        "ghgPerCapita": 2.0527356,
        "globalSharePct": null,
        "peopleAffected": null,
        "peopleAffectedPer1000": null,
        "economicLossPctGDP": null
      }
    ]
  },
  "sstSeries": {
    "TON": [
      {
        "year": 2017,
        "sstAnomaly": 0.6
      },
      {
        "year": 2018,
        "sstAnomaly": 0.5
      },
      {
        "year": 2019,
        "sstAnomaly": 0.5
      },
      {
        "year": 2020,
        "sstAnomaly": 0.7
      },
      {
        "year": 2021,
        "sstAnomaly": 0.8
      },
      {
        "year": 2022,
        "sstAnomaly": 1.1
      },
      {
        "year": 2023,
        "sstAnomaly": 0.5
      },
      {
        "year": 2024,
        "sstAnomaly": 0.6
      },
      {
        "year": 2025,
        "sstAnomaly": 0.6
      }
    ],
    "WSM": [
      {
        "year": 2017,
        "sstAnomaly": 0.6
      },
      {
        "year": 2018,
        "sstAnomaly": 0.6
      },
      {
        "year": 2019,
        "sstAnomaly": 0.7
      },
      {
        "year": 2020,
        "sstAnomaly": 0.6
      },
      {
        "year": 2021,
        "sstAnomaly": 0.4
      },
      {
        "year": 2022,
        "sstAnomaly": 0.3
      },
      {
        "year": 2023,
        "sstAnomaly": 0.6
      },
      {
        "year": 2024,
        "sstAnomaly": 0.8
      },
      {
        "year": 2025,
        "sstAnomaly": 0.5
      }
    ],
    "VUT": [
      {
        "year": 2017,
        "sstAnomaly": 0.5
      },
      {
        "year": 2018,
        "sstAnomaly": 0.4
      },
      {
        "year": 2019,
        "sstAnomaly": 0.3
      },
      {
        "year": 2020,
        "sstAnomaly": 0.5
      },
      {
        "year": 2021,
        "sstAnomaly": 0.6
      },
      {
        "year": 2022,
        "sstAnomaly": 1.1
      },
      {
        "year": 2023,
        "sstAnomaly": 0.5
      },
      {
        "year": 2024,
        "sstAnomaly": 0.7
      },
      {
        "year": 2025,
        "sstAnomaly": 0.8
      }
    ],
    "FJI": [
      {
        "year": 2017,
        "sstAnomaly": 0.5
      },
      {
        "year": 2018,
        "sstAnomaly": 0.4
      },
      {
        "year": 2019,
        "sstAnomaly": 0.4
      },
      {
        "year": 2020,
        "sstAnomaly": 0.5
      },
      {
        "year": 2021,
        "sstAnomaly": 0.7
      },
      {
        "year": 2022,
        "sstAnomaly": 1.1
      },
      {
        "year": 2023,
        "sstAnomaly": 0.5
      },
      {
        "year": 2024,
        "sstAnomaly": 0.6
      },
      {
        "year": 2025,
        "sstAnomaly": 0.7
      }
    ],
    "FSM": [
      {
        "year": 2017,
        "sstAnomaly": 0.7
      },
      {
        "year": 2018,
        "sstAnomaly": 0.6
      },
      {
        "year": 2019,
        "sstAnomaly": 0.5
      },
      {
        "year": 2020,
        "sstAnomaly": 0.7
      },
      {
        "year": 2021,
        "sstAnomaly": 0.7
      },
      {
        "year": 2022,
        "sstAnomaly": 0.6
      },
      {
        "year": 2023,
        "sstAnomaly": 0.7
      },
      {
        "year": 2024,
        "sstAnomaly": 0.8
      },
      {
        "year": 2025,
        "sstAnomaly": 0.9
      }
    ],
    "SLB": [
      {
        "year": 2017,
        "sstAnomaly": 0.7
      },
      {
        "year": 2018,
        "sstAnomaly": 0.6
      },
      {
        "year": 2019,
        "sstAnomaly": 0.5
      },
      {
        "year": 2020,
        "sstAnomaly": 0.8
      },
      {
        "year": 2021,
        "sstAnomaly": 0.6
      },
      {
        "year": 2022,
        "sstAnomaly": 0.7
      },
      {
        "year": 2023,
        "sstAnomaly": 0.6
      },
      {
        "year": 2024,
        "sstAnomaly": 0.9
      },
      {
        "year": 2025,
        "sstAnomaly": 0.9
      }
    ],
    "PNG": [
      {
        "year": 2017,
        "sstAnomaly": 0.7
      },
      {
        "year": 2018,
        "sstAnomaly": 0.5
      },
      {
        "year": 2019,
        "sstAnomaly": 0.3
      },
      {
        "year": 2020,
        "sstAnomaly": 0.8
      },
      {
        "year": 2021,
        "sstAnomaly": 0.6
      },
      {
        "year": 2022,
        "sstAnomaly": 0.8
      },
      {
        "year": 2023,
        "sstAnomaly": 0.6
      },
      {
        "year": 2024,
        "sstAnomaly": 0.9
      },
      {
        "year": 2025,
        "sstAnomaly": 1.1
      }
    ],
    "PLW": [
      {
        "year": 2017,
        "sstAnomaly": 0.7
      },
      {
        "year": 2018,
        "sstAnomaly": 0.5
      },
      {
        "year": 2019,
        "sstAnomaly": 0.3
      },
      {
        "year": 2020,
        "sstAnomaly": 0.7
      },
      {
        "year": 2021,
        "sstAnomaly": 0.8
      },
      {
        "year": 2022,
        "sstAnomaly": 0.8
      },
      {
        "year": 2023,
        "sstAnomaly": 0.7
      },
      {
        "year": 2024,
        "sstAnomaly": 0.8
      },
      {
        "year": 2025,
        "sstAnomaly": 0.9
      }
    ],
    "KIR": [
      {
        "year": 2017,
        "sstAnomaly": 0.2
      },
      {
        "year": 2018,
        "sstAnomaly": 0.4
      },
      {
        "year": 2019,
        "sstAnomaly": 0.8
      },
      {
        "year": 2020,
        "sstAnomaly": 0.2
      },
      {
        "year": 2021,
        "sstAnomaly": -0.3
      },
      {
        "year": 2022,
        "sstAnomaly": -0.6
      },
      {
        "year": 2023,
        "sstAnomaly": 0.7
      },
      {
        "year": 2024,
        "sstAnomaly": 0.8
      },
      {
        "year": 2025,
        "sstAnomaly": 0.1
      }
    ],
    "TUV": [
      {
        "year": 2017,
        "sstAnomaly": 0.5
      },
      {
        "year": 2018,
        "sstAnomaly": 0.6
      },
      {
        "year": 2019,
        "sstAnomaly": 0.8
      },
      {
        "year": 2020,
        "sstAnomaly": 0.6
      },
      {
        "year": 2021,
        "sstAnomaly": 0.2
      },
      {
        "year": 2022,
        "sstAnomaly": -0.1
      },
      {
        "year": 2023,
        "sstAnomaly": 0.6
      },
      {
        "year": 2024,
        "sstAnomaly": 0.9
      },
      {
        "year": 2025,
        "sstAnomaly": 0.4
      }
    ]
  },
  "metrics": {
    "countries": 10,
    "period": "2000\u20132024",
    "maxLossCountry": "Tonga",
    "maxLossValue": 8.22,
    "highestAffectedCountry": "Tuvalu",
    "highestAffectedValue": 486.7,
    "combinedGlobalShare": 0.115
  }
} as const;
