/**
 * Generated by scripts/build_consequence_data.mjs from official Pacific Data Hub .Stat SDG 11 CSV extracts.
 * Dataflow: SPC:DF_SDG_11(4.4), VC_DSR_LSGP and VC_DSR_AFFCT. Blank years are null; observed zeros are retained.
 */

export type ConsequenceAnnual = { year: number; officialLossPctGDP: number | null; directlyAffected: number | null };
export type ConsequencePlace = { code: string; name: string; meanOfficialLossPctGDP: number; meanDirectlyAffected: number; lossYears: number; affectedYears: number; annual: ConsequenceAnnual[] };

export const consequenceMeta = {
  period: "2005–2023",
  comparablePlaces: 12,
  dataflow: "SPC:DF_SDG_11(4.4)",
  lossIndicator: "VC_DSR_LSGP",
  affectedIndicator: "VC_DSR_AFFCT",
  lossSource: "Pacific Community / Pacific Data Hub .Stat · direct economic loss attributed to disasters relative to GDP [SDG 1.5.2, 11.5.2]",
  affectedSource: "Pacific Community / Pacific Data Hub .Stat · directly affected persons attributed to disasters",
  sourceAgency: "United Nations Office for Disaster Risk Reduction · Sendai Framework Monitoring System (2026)",
  sourceNote: "Values are submitted by designated national focal points; some may not have followed an official validation process and may be revised. Observed zero is a value; a blank year has no record.",
  lossUrl: "https://stats-sdmx-disseminate.pacificdata.org/rest/v1/data/SPC,DF_SDG_11,4.4/A..VC_DSR_LSGP............?format=csvfile",
  affectedUrl: "https://stats-sdmx-disseminate.pacificdata.org/rest/v1/data/SPC,DF_SDG_11,4.4/A..VC_DSR_AFFCT............?format=csvfile",
} as const;

export const consequencePlaces: ConsequencePlace[] = [
  {
    "code": "FJ",
    "name": "Fiji",
    "meanOfficialLossPctGDP": 0.0289,
    "meanDirectlyAffected": 118309,
    "lossYears": 9,
    "affectedYears": 10,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2015,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2016,
        "officialLossPctGDP": 0.18,
        "directlyAffected": 633584
      },
      {
        "year": 2017,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2018,
        "officialLossPctGDP": 0.01,
        "directlyAffected": 155725
      },
      {
        "year": 2019,
        "officialLossPctGDP": 0,
        "directlyAffected": 78045
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0.05,
        "directlyAffected": 235921
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0.02,
        "directlyAffected": 78029
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0,
        "directlyAffected": 1787
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "KI",
    "name": "Kiribati",
    "meanOfficialLossPctGDP": 0.0267,
    "meanDirectlyAffected": 498,
    "lossYears": 3,
    "affectedYears": 6,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": 85
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": 0,
        "directlyAffected": 44
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": 2507
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2018,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": 3
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0,
        "directlyAffected": 15
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0.08,
        "directlyAffected": 333
      },
      {
        "year": 2022,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "MH",
    "name": "Marshall Islands",
    "meanOfficialLossPctGDP": 0.005,
    "meanDirectlyAffected": 22495,
    "lossYears": 8,
    "affectedYears": 8,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2016,
        "officialLossPctGDP": 0.01,
        "directlyAffected": 27452
      },
      {
        "year": 2017,
        "officialLossPctGDP": 0,
        "directlyAffected": 7029
      },
      {
        "year": 2018,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2019,
        "officialLossPctGDP": 0,
        "directlyAffected": 35844
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0,
        "directlyAffected": 56718
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0.03,
        "directlyAffected": 52914
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "FM",
    "name": "Micronesia",
    "meanOfficialLossPctGDP": 0.005,
    "meanDirectlyAffected": 7435,
    "lossYears": 4,
    "affectedYears": 6,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": 0,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": 7600
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2018,
        "officialLossPctGDP": 0,
        "directlyAffected": 1266
      },
      {
        "year": 2019,
        "officialLossPctGDP": 0.02,
        "directlyAffected": 20732
      },
      {
        "year": 2020,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0,
        "directlyAffected": 15010
      },
      {
        "year": 2022,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "NR",
    "name": "Nauru",
    "meanOfficialLossPctGDP": 0,
    "meanDirectlyAffected": 1641,
    "lossYears": 3,
    "affectedYears": 4,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2018,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2019,
        "officialLossPctGDP": 0,
        "directlyAffected": 39
      },
      {
        "year": 2020,
        "officialLossPctGDP": null,
        "directlyAffected": 1133
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0,
        "directlyAffected": 5393
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "PW",
    "name": "Palau",
    "meanOfficialLossPctGDP": 0.035,
    "meanDirectlyAffected": 7752,
    "lossYears": 2,
    "affectedYears": 4,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": 11009
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2018,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2020,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0.06,
        "directlyAffected": 20000
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0.01,
        "directlyAffected": 0
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "meanOfficialLossPctGDP": 0,
    "meanDirectlyAffected": 3297,
    "lossYears": 1,
    "affectedYears": 1,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2018,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0,
        "directlyAffected": 3297
      },
      {
        "year": 2021,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2022,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "WS",
    "name": "Samoa",
    "meanOfficialLossPctGDP": 0,
    "meanDirectlyAffected": 8462,
    "lossYears": 2,
    "affectedYears": 5,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2018,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": 5700
      },
      {
        "year": 2020,
        "officialLossPctGDP": null,
        "directlyAffected": 195
      },
      {
        "year": 2021,
        "officialLossPctGDP": null,
        "directlyAffected": 15
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0,
        "directlyAffected": 16607
      },
      {
        "year": 2023,
        "officialLossPctGDP": 0,
        "directlyAffected": 19794
      }
    ]
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "meanOfficialLossPctGDP": 0.015,
    "meanDirectlyAffected": 59892,
    "lossYears": 10,
    "affectedYears": 9,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": 0.01,
        "directlyAffected": 7577
      },
      {
        "year": 2014,
        "officialLossPctGDP": 0,
        "directlyAffected": 14831
      },
      {
        "year": 2015,
        "officialLossPctGDP": 0.03,
        "directlyAffected": 185886
      },
      {
        "year": 2016,
        "officialLossPctGDP": 0.02,
        "directlyAffected": 60858
      },
      {
        "year": 2017,
        "officialLossPctGDP": 0.03,
        "directlyAffected": 51465
      },
      {
        "year": 2018,
        "officialLossPctGDP": 0.05,
        "directlyAffected": 194155
      },
      {
        "year": 2019,
        "officialLossPctGDP": 0.01,
        "directlyAffected": 1833
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0,
        "directlyAffected": 2339
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0,
        "directlyAffected": null
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0,
        "directlyAffected": 20080
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "TO",
    "name": "Tonga",
    "meanOfficialLossPctGDP": 0.0086,
    "meanDirectlyAffected": 6155,
    "lossYears": 7,
    "affectedYears": 13,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": 7
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2013,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2014,
        "officialLossPctGDP": 0.04,
        "directlyAffected": 0
      },
      {
        "year": 2015,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2016,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2017,
        "officialLossPctGDP": 0,
        "directlyAffected": 0
      },
      {
        "year": 2018,
        "officialLossPctGDP": 0.02,
        "directlyAffected": 80003
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2020,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2021,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2022,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "TV",
    "name": "Tuvalu",
    "meanOfficialLossPctGDP": 0.1167,
    "meanDirectlyAffected": 1568,
    "lossYears": 3,
    "affectedYears": 7,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2016,
        "officialLossPctGDP": 0.09,
        "directlyAffected": 1003
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2018,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": 0
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0.26,
        "directlyAffected": 2266
      },
      {
        "year": 2021,
        "officialLossPctGDP": null,
        "directlyAffected": 6
      },
      {
        "year": 2022,
        "officialLossPctGDP": 0,
        "directlyAffected": 7700
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": null
      }
    ]
  },
  {
    "code": "VU",
    "name": "Vanuatu",
    "meanOfficialLossPctGDP": 0.1733,
    "meanDirectlyAffected": 51126,
    "lossYears": 3,
    "affectedYears": 5,
    "annual": [
      {
        "year": 2005,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2006,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2007,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2008,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2009,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2010,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2011,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2012,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2013,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2014,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2015,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2016,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2017,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2018,
        "officialLossPctGDP": 0.41,
        "directlyAffected": 7286
      },
      {
        "year": 2019,
        "officialLossPctGDP": null,
        "directlyAffected": 18
      },
      {
        "year": 2020,
        "officialLossPctGDP": 0.11,
        "directlyAffected": 246802
      },
      {
        "year": 2021,
        "officialLossPctGDP": 0,
        "directlyAffected": 1400
      },
      {
        "year": 2022,
        "officialLossPctGDP": null,
        "directlyAffected": null
      },
      {
        "year": 2023,
        "officialLossPctGDP": null,
        "directlyAffected": 124
      }
    ]
  }
];
