import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const input = path.join(root, 'data-sources/official/pdh_rainfall_anomaly.csv');
const output = path.join(root, 'client/src/data/rainfallData.ts');
const nameByCode = {
  AS: 'American Samoa', CK: 'Cook Islands', FJ: 'Fiji', FM: 'Micronesia', GU: 'Guam', KI: 'Kiribati', MH: 'Marshall Islands', MP: 'Northern Mariana Islands', NC: 'New Caledonia', NR: 'Nauru', NU: 'Niue', PF: 'French Polynesia', PG: 'Papua New Guinea', PN: 'Pitcairn Islands', PW: 'Palau', SB: 'Solomon Islands', TK: 'Tokelau', TO: 'Tonga', TV: 'Tuvalu', VU: 'Vanuatu', WF: 'Wallis and Futuna', WS: 'Samoa',
};

const lines = fs.readFileSync(input, 'utf8').trim().split(/\r?\n/);
const header = lines.shift().split(',');
const index = Object.fromEntries(header.map((field, position) => [field, position]));
const grouped = new Map();
for (const line of lines) {
  const cells = line.split(',');
  const code = cells[index.GEO_PICT];
  const year = Number(cells[index.TIME_PERIOD]);
  const value = Number(cells[index.OBS_VALUE]);
  if (!nameByCode[code] || !Number.isFinite(year) || !Number.isFinite(value)) continue;
  const series = grouped.get(code) ?? [];
  series.push({ year, value });
  grouped.set(code, series);
}
const countries = [...grouped.entries()].sort(([a], [b]) => nameByCode[a].localeCompare(nameByCode[b])).map(([code, series]) => {
  series.sort((a, b) => a.year - b.year);
  const values = series.map((point) => point.value);
  return {
    code,
    name: nameByCode[code],
    series,
    summary: {
      firstYear: series[0].year,
      first: series[0].value,
      latestYear: series.at(-1).year,
      latest: series.at(-1).value,
      records: series.length,
      min: Math.min(...values),
      max: Math.max(...values),
    },
  };
});
const outputData = {
  meta: {
    dataflow: 'SPC:DF_CLIMATE_CHANGE(1.0)',
    indicator: 'RAIN_ANOM',
    unit: 'MM',
    observations: countries.reduce((total, country) => total + country.series.length, 0),
    places: countries.length,
    period: `${Math.min(...countries.map((country) => country.summary.firstYear))}–${Math.max(...countries.map((country) => country.summary.latestYear))}`,
    source: 'Pacific Community / Pacific Data Hub .Stat',
    sourceUrl: 'https://stats-sdmx-disseminate.pacificdata.org/rest/v1/data/SPC,DF_CLIMATE_CHANGE,1.0/A.RAIN_ANOM..?format=csvfile',
  },
  countries,
};
fs.writeFileSync(output, `/** Generated by scripts/build_rainfall_data.mjs from the official Pacific Data Hub rainfall-anomaly extract. Do not manually edit. */\nexport type RainfallPoint = { year: number; value: number };\nexport type RainfallCountry = { code: string; name: string; series: RainfallPoint[]; summary: { firstYear: number; first: number; latestYear: number; latest: number; records: number; min: number; max: number } };\nexport type RainfallMeta = { dataflow: string; indicator: string; unit: string; observations: number; places: number; period: string; source: string; sourceUrl: string };\nexport const rainfallData: { meta: RainfallMeta; countries: RainfallCountry[] } = ${JSON.stringify(outputData)};\n`);
console.log(JSON.stringify({ output: path.relative(root, output), observations: outputData.meta.observations, places: outputData.meta.places, period: outputData.meta.period }, null, 2));
