/**
 * Signal Room consequence-data transformer.
 *
 * Uses two official Pacific Data Hub .Stat SDG 11 extracts downloaded from
 * SPC:DF_SDG_11(4.4): VC_DSR_LSGP and VC_DSR_AFFCT. Blank years remain null;
 * an observed zero remains zero. The UNDRR source note is preserved in output.
 */
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const lossPath = resolve("data-sources/official/pdh_official_direct_disaster_loss.csv");
const affectedPath = resolve("data-sources/official/pdh_official_directly_affected.csv");
const outputPath = resolve("client/src/data/consequenceData.ts");

const names = {
  FJ: "Fiji", FM: "Micronesia", KI: "Kiribati", MH: "Marshall Islands", NR: "Nauru", PG: "Papua New Guinea",
  PW: "Palau", SB: "Solomon Islands", TO: "Tonga", TV: "Tuvalu", VU: "Vanuatu", WS: "Samoa",
};

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    if (quoted) {
      if (char === '"' && text[index + 1] === '"') { cell += '"'; index += 1; }
      else if (char === '"') quoted = false;
      else cell += char;
    } else if (char === '"') quoted = true;
    else if (char === ",") { row.push(cell); cell = ""; }
    else if (char === "\n") { row.push(cell.replace(/\r$/, "")); rows.push(row); row = []; cell = ""; }
    else cell += char;
  }
  if (cell || row.length) { row.push(cell.replace(/\r$/, "")); rows.push(row); }
  const [header, ...body] = rows;
  return body.filter((values) => values.length === header.length).map((values) => Object.fromEntries(header.map((key, index) => [key, values[index]])));
}

function seriesByPlace(rows) {
  const values = new Map();
  rows.forEach((row) => {
    const code = row.REF_AREA;
    const year = Number(row.TIME_PERIOD);
    const observed = Number(row.OBS_VALUE);
    if (!names[code] || !Number.isFinite(year) || !Number.isFinite(observed)) return;
    if (!values.has(code)) values.set(code, new Map());
    values.get(code).set(year, observed);
  });
  return values;
}

const lossRows = parseCsv(await readFile(lossPath, "utf8"));
const affectedRows = parseCsv(await readFile(affectedPath, "utf8"));
const lossByPlace = seriesByPlace(lossRows);
const affectedByPlace = seriesByPlace(affectedRows);
const codes = [...new Set([...lossByPlace.keys(), ...affectedByPlace.keys()])].sort((a, b) => names[a].localeCompare(names[b]));
const allYears = [...lossRows, ...affectedRows].map((row) => Number(row.TIME_PERIOD)).filter(Number.isFinite);
const firstYear = Math.min(...allYears);
const lastYear = Math.max(...allYears);

const average = (values) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const places = codes.map((code) => {
  const losses = lossByPlace.get(code) ?? new Map();
  const affected = affectedByPlace.get(code) ?? new Map();
  const annual = Array.from({ length: lastYear - firstYear + 1 }, (_, offset) => {
    const year = firstYear + offset;
    return {
      year,
      officialLossPctGDP: losses.has(year) ? Number(losses.get(year).toFixed(6)) : null,
      directlyAffected: affected.has(year) ? Number(affected.get(year).toFixed(0)) : null,
    };
  });
  const observedLosses = annual.flatMap((row) => row.officialLossPctGDP === null ? [] : [row.officialLossPctGDP]);
  const observedAffected = annual.flatMap((row) => row.directlyAffected === null ? [] : [row.directlyAffected]);
  return {
    code,
    name: names[code],
    meanOfficialLossPctGDP: Number(average(observedLosses).toFixed(4)),
    meanDirectlyAffected: Number(average(observedAffected).toFixed(0)),
    lossYears: observedLosses.length,
    affectedYears: observedAffected.length,
    annual,
  };
});

const sourceUrl = "https://stats-sdmx-disseminate.pacificdata.org/rest/v1/data/SPC,DF_SDG_11,4.4/A..VC_DSR_LSGP............?format=csvfile";
const affectedUrl = "https://stats-sdmx-disseminate.pacificdata.org/rest/v1/data/SPC,DF_SDG_11,4.4/A..VC_DSR_AFFCT............?format=csvfile";
const output = `/**
 * Generated by scripts/build_consequence_data.mjs from official Pacific Data Hub .Stat SDG 11 CSV extracts.
 * Dataflow: SPC:DF_SDG_11(4.4), VC_DSR_LSGP and VC_DSR_AFFCT. Blank years are null; observed zeros are retained.
 */

export type ConsequenceAnnual = { year: number; officialLossPctGDP: number | null; directlyAffected: number | null };
export type ConsequencePlace = { code: string; name: string; meanOfficialLossPctGDP: number; meanDirectlyAffected: number; lossYears: number; affectedYears: number; annual: ConsequenceAnnual[] };

export const consequenceMeta = {
  period: "${firstYear}–${lastYear}",
  comparablePlaces: ${places.length},
  dataflow: "SPC:DF_SDG_11(4.4)",
  lossIndicator: "VC_DSR_LSGP",
  affectedIndicator: "VC_DSR_AFFCT",
  lossSource: "Pacific Community / Pacific Data Hub .Stat · direct economic loss attributed to disasters relative to GDP [SDG 1.5.2, 11.5.2]",
  affectedSource: "Pacific Community / Pacific Data Hub .Stat · directly affected persons attributed to disasters",
  sourceAgency: "United Nations Office for Disaster Risk Reduction · Sendai Framework Monitoring System (2026)",
  sourceNote: "Values are submitted by designated national focal points; some may not have followed an official validation process and may be revised. Observed zero is a value; a blank year has no record.",
  lossUrl: "${sourceUrl}",
  affectedUrl: "${affectedUrl}",
} as const;

export const consequencePlaces: ConsequencePlace[] = ${JSON.stringify(places, null, 2)};
`;

await writeFile(outputPath, output, "utf8");
console.log(`Wrote ${outputPath} with ${places.length} official Pacific Data Hub places (${firstYear}–${lastYear}).`);
